{
  "id": "CVE-2018-16168",
  "assigner": "vultures@jpcert.or.jp",
  "last_modified": "2019-01-15T13:45:15.357",
  "vulnerable_configuration": [
    "cpe:2.3:a:jpcert:logontracer:1.0.0:*:*:*:*:*:*:*",
    "cpe:2.3:a:jpcert:logontracer:1.0.1:*:*:*:*:*:*:*",
    "cpe:2.3:a:jpcert:logontracer:1.0.2:*:*:*:*:*:*:*",
    "cpe:2.3:a:jpcert:logontracer:1.0.3:*:*:*:*:*:*:*",
    "cpe:2.3:a:jpcert:logontracer:1.1.0:*:*:*:*:*:*:*",
    "cpe:2.3:a:jpcert:logontracer:1.1.1:*:*:*:*:*:*:*",
    "cpe:2.3:a:jpcert:logontracer:1.2.0:*:*:*:*:*:*:*"
  ],
  "cwe": "en",
  "summary": "LogonTracer 1.2.0 and earlier allows remote attackers to conduct Python code injection attacks via unspecified vectors.",
  "references": [
    "https://github.com/JPCERTCC/LogonTracer/releases/tag/v1.2.1",
    "https://jvn.jp/en/vu/JVNVU98026636/index.html"
  ]
}