{
  "id": "CVE-2019-8397",
  "assigner": "cve@mitre.org",
  "last_modified": "2019-02-19T21:04:33.377",
  "vulnerable_configuration": [
    "cpe:2.3:a:hdfgroup:hdf5:1.10.4:*:*:*:*:*:*:*"
  ],
  "cwe": "en",
  "summary": "An issue was discovered in the HDF HDF5 1.10.4 library. There is an out of bounds read in the function H5T_close_real in H5T.c.",
  "references": [
    "https://github.com/magicSwordsMan/PAAFS/tree/master/vul5"
  ]
}